### ISSUE TITLE
event management

### ISSUE THREAD

**Issue by Kflash** [jeibo/jeibo#6]
This is just a reminder...

Jeibo will have it's own Event system including an emitter developed from scratch. This will take awhile, but it already contain the basic functions such as add, remove, once, invoke and a method to keep track on each listeners added per type.

Need to find ways to test the emitter without transpiling it down to ES5 and bundling it as it's own module.

### Requirements
- performance
- stability
- promises

**Comment by TrySound** [comment]
@Kflash If you want to test part of functionality, you may move it in separate module. Rollup constrain you to test only user API. This makes tests more consistent. But you may export some independent API from entry point.

I don't think rewriting everything again and again is a good idea. Even own array.map is a bit opinionated. Engine can optimise it internally and benchmarks doesn't give you objective information. Rich Harris likes to talk about developer sanity. It's about it.

**Comment by Kflash** [comment]
I think I figured out a way to solve testing, but still tempted to swap to TypeScript again.

What do you mean when you say rewrite? Basicly I did some quick, dirty things to get the config working. And regarding array.map. Native Array.map also let you iterate objects. I saw no point to iterate objects when I was only looping through arrays. And since 2012 Array.map have been slow. But probably changed anno 2016.

For other components in this project - events, log etc. There are mostly no good alternatives, or the good alternatives are outdated 3 years ago. And relying on 3rdParty NPM packages can be little risky or too bloated. It all depends. 

This is the main reason why this project will take time. It's best too do it correct the first time, so I'm avoiding tons of issue tickets.

I'm very soon to publish a basic emitter now.

**Comment by Kflash** [comment]
Closing because I'm going to extract the emitter from the core and use it as a dependency.

**Comment by Kflash** [comment]
Events have been extracted out and are now a dependency. Found here: https://github.com/jeibo/nemitter
