### ISSUE TITLE
require vs preprocessors

### ISSUE THREAD

**Issue by Kflash** [jeibo/jeibo#9]
The decision is not taken yet, but I think it will be easier with a plugin based solution rather then a require flag in CLI.

In this way the Jeibo core will remain small, and compact.

@TrySound Do you have any ideas regarding this? Take a look at the readme to understand what this is about.

**Comment by TrySound** [comment]
What is the question?)

**Comment by Kflash** [comment]
Question is what do you think is the best approach?  Require or a plugin

**Comment by TrySound** [comment]
I guess require is less opinionated and short.

**Comment by Kflash** [comment]
@TrySound Thing will take very long time because I have very little time to work on private projects this days, but I have a running solution locale.

However. I'm still confused if I should add a plugin-solution ala Rollup or not. Such solution will let you transpile the files in the same way and will provide the possibility to for example, use of using coffee script, typescript etc.

This seems to be the solution. And this plugins will be activated through the CLI.
By default there will be build in support for both Babel and Buble. But Buble will be activated by default. 

The CLI flag will look like this for Buble:

`--transpile buble` or `-t buble`

and with a typescript plugin

`-t typescript`

I also plan to add support for other plugins such as reporters. 

The code will go online soon as this things are sorted, and the core are stable.

**Comment by Kflash** [comment]
@TrySound For now I park this project. I face too much issues with Rollup now , and my time is up for the next days.
